[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Gurukul Robot-Learning Extension"
author = "Gurukul contributors"
maintainer = "Gurukul contributors"
description = "Research tasks and tools for robot learning in Isaac Lab."
repository = "https://github.com/shivam-sood00/Gurukul"
keywords = ["extension", "Gurukul", "isaaclab", "robot-learning"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "Gurukul"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
